window.FESTIVAL_CONFIG = {
  id: 'shavuot',
  name: 'Torah-kers',
  subtitle: 'Shavuot Edition',
  emoji: '📜',
  categories: ['People', 'Torah & Learning', 'Food & Customs', 'Fun & Silly'],
  categoryLabels: {
    'People': 'PEOPLE',
    'Torah & Learning': 'TORAH & LEARNING',
    'Food & Customs': 'FOOD & CUSTOMS',
    'Fun & Silly': 'FUN & SILLY'
  },
  categoryColors: {
    'People': '#27ae60',
    'Torah & Learning': '#2b7bb9',
    'Food & Customs': '#e67e22',
    'Fun & Silly': '#8e44ad'
  },
  categoryClasses: {
    'People': 'cat-people',
    'Torah & Learning': 'cat-torah',
    'Food & Customs': 'cat-food',
    'Fun & Silly': 'cat-fun'
  },
  cardBackImage: null,
  themeColors: {
    gold: '#4a9e5c',
    goldLight: '#6bc47d',
    headerBg: '#1a3a2e'
  },
  storagePrefix: 'torahkers',
  defaultCards: [
    // ===== PEOPLE (13 cards) =====
    {id: 1, title: "Moshe Rabbeinu", cat: "People", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The greatest prophet who ever lived, who ascended Har Sinai to receive the Torah directly from Hashem. Spent 40 days and nights up there without food or water, which makes your Yom Kippur fast look like a light snack."},
    {id: 2, title: "Ruth The Moavite", cat: "People", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The ultimate convert whose story we read on Shavuot. Her famous declaration to Naomi — 'Where you go, I will go' — set the gold standard for loyalty and commitment to the Jewish people."},
    {id: 3, title: "Naomi Returns Home", cat: "People", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "After losing her husband and two sons in Moav, Naomi returned to Beit Lechem bitter and broken. She told everyone to call her Mara, but her story was far from over — her daughter-in-law Ruth would change everything."},
    {id: 4, title: "Boaz The Redeemer", cat: "People", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The wealthy landowner of Beit Lechem who noticed Ruth gleaning in his fields and treated her with extraordinary kindness. He married Ruth and became the great-grandfather of King David. Proof that being a mensch pays off."},
    {id: 5, title: "King David", cat: "People", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "Born and died on Shavuot according to tradition, making him the ultimate Shavuot baby. Descended from Ruth and Boaz, he authored Tehillim and established Yerushalayim as the eternal capital. Not bad for a shepherd boy."},
    {id: 6, title: "Rabbi Akiva's Journey", cat: "People", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "Started learning Torah at age 40, completely illiterate, after watching water wear away stone. Became one of the greatest Torah scholars in history with 24,000 students. The original proof that it's never too late to start learning."},
    {id: 7, title: "Yitro At Sinai", cat: "People", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "Moshe's father-in-law and a former idolatrous priest who heard about the miracles and came running to join the Jewish people. The parsha of Matan Torah bears his name, reminding us that the Torah was given for everyone."},
    {id: 8, title: "Baby Moshe's Test", cat: "People", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "As an infant in Pharaoh's palace, Moshe reached for the king's crown, alarming the advisors. An angel guided his hand to the hot coal instead, burning his mouth and giving him a speech impediment — but saving his life. The original 'hot take.'"},
    {id: 9, title: "Bnei Yisrael Together", cat: "People", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "The entire nation camped at Har Sinai 'as one person with one heart' — the Torah uses the singular form to describe their unity. Apparently the only time in Jewish history everyone agreed on something."},
    {id: 10, title: "Shlomo HaMelech", cat: "People", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "King David's son, who built the Beit HaMikdash and authored Shir HaShirim, which is read as an allegory of Hashem's love for Israel. Traditionally, Shir HaShirim's themes of love and devotion connect deeply to the Shavuot covenant."},
    {id: 11, title: "Orpah Turns Back", cat: "People", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "Naomi's other daughter-in-law who kissed her goodbye and returned to Moav, while Ruth clung on. According to the Midrash, she became the ancestor of Goliath — making the David vs. Goliath story a family affair."},
    {id: 12, title: "Har Sinai Converts", cat: "People", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "According to tradition, the souls of all future converts were present at Sinai for the giving of the Torah. This is why we read Megillat Ruth on Shavuot — to honor those who choose to join the covenant."},
    {id: 13, title: "The Kohanim's Role", cat: "People", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "On Shavuot in the Beit HaMikdash, the Kohanim performed special services including the offering of the Shtei HaLechem. They also blessed the people with Birkat Kohanim, a tradition that continues in shuls to this day."},

    // ===== TORAH & LEARNING (13 cards) =====
    {id: 14, title: "Matan Torah", cat: "Torah & Learning", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The main event — Hashem giving the Torah to Bnei Yisrael at Har Sinai, complete with thunder, lightning, shofar blasts, and a mountain held over their heads. The most dramatic book launch in history."},
    {id: 15, title: "Aseret HaDibrot", cat: "Torah & Learning", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The Ten Commandments, spoken by Hashem directly to the entire nation. We stand during their reading on Shavuot to relive the experience. Covers everything from belief in God to not coveting your neighbor's donkey."},
    {id: 16, title: "Tikkun Leil Shavuot", cat: "Torah & Learning", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The custom of staying up all night learning Torah on Shavuot eve. Established by the Arizal to rectify the fact that Bnei Yisrael overslept on the morning of Matan Torah. We've been compensating ever since."},
    {id: 17, title: "Megillat Ruth", cat: "Torah & Learning", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "One of the five Megillot, read on Shavuot. It tells the story of loyalty, conversion, and redemption set during the harvest season. Also the source of every Jewish grandmother's favorite matchmaking advice."},
    {id: 18, title: "Two Luchot HaBrit", cat: "Torah & Learning", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The two stone tablets on which Hashem inscribed the Ten Commandments. The first set was smashed by Moshe when he saw the Golden Calf. The second set was carved by Moshe himself — the original 'second edition, revised.'"},
    {id: 19, title: "Akdamut Poem", cat: "Torah & Learning", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "An Aramaic liturgical poem recited in Ashkenazi shuls before the Torah reading on Shavuot. Written by Rabbi Meir ben Yitzchak of Worms in the 11th century, it has 90 lines in a double alphabetical acrostic. Peak medieval poetry nerdery."},
    {id: 20, title: "Yizkor On Shavuot", cat: "Torah & Learning", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The memorial prayer service recited on the second day of Shavuot (and three other festivals). A solemn moment amid the celebration, connecting past generations to the eternal Torah they cherished."},
    {id: 21, title: "Hallel With Bracha", cat: "Torah & Learning", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The full Hallel is recited on both days of Shavuot with a blessing — unlike Pesach where it's abbreviated after the first day. Shavuot doesn't play favorites with its days of joy."},
    {id: 22, title: "Torah Reading Selection", cat: "Torah & Learning", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "On the first day of Shavuot, we read the account of Matan Torah from Parshat Yitro. On the second day, we read from Re'eh about the Shalosh Regalim. The Haftarah features Yechezkel's vision of the Divine Chariot — no pressure."},
    {id: 23, title: "Azharot Liturgy", cat: "Torah & Learning", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "Sephardi communities recite Azharot, poetic enumerations of all 613 mitzvot, on Shavuot. Because if you're celebrating receiving the Torah, you might as well review the entire syllabus."},
    {id: 24, title: "Naaseh V'Nishma", cat: "Torah & Learning", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The famous declaration 'We will do and we will hear' that Bnei Yisrael proclaimed at Sinai, agreeing to the Torah's commandments before even knowing what they were. History's most enthusiastic terms-of-service acceptance."},
    {id: 25, title: "Sefirat HaOmer Link", cat: "Torah & Learning", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The 49-day count from Pesach leads directly to Shavuot, connecting physical freedom to spiritual purpose. Each day is a step of refinement, like a spiritual countdown calendar — but without the chocolate."},
    {id: 26, title: "Mountain Over Heads", cat: "Torah & Learning", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "The Talmud teaches that Hashem held Har Sinai over the people like an upside-down barrel, saying 'Accept the Torah or this will be your burial place.' The ultimate offer you can't refuse. The Gemara debates whether this was literal or metaphorical."},

    // ===== FOOD & CUSTOMS (12 cards) =====
    {id: 27, title: "Classic Cheesecake", cat: "Food & Customs", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The undisputed MVP of Shavuot desserts. Whether New York style, no-bake, or topped with fruit, every family has strong opinions about whose recipe is best. Wars have been fought over less."},
    {id: 28, title: "Cheese Blintzes", cat: "Food & Customs", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "Delicate crepes filled with sweetened cheese and pan-fried to golden perfection. Traditionally served with sour cream or fruit compote. The Torah was rolled up in two scrolls like blintzes — or so the minhag claims."},
    {id: 29, title: "Dairy Foods Tradition", cat: "Food & Customs", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "Multiple reasons are given for eating dairy on Shavuot: the Torah is compared to milk and honey, Bnei Yisrael didn't yet know the laws of shechita, and the gematria of 'chalav' equals 40. Pick your favorite explanation."},
    {id: 30, title: "Greenery And Flowers", cat: "Food & Customs", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "Shuls and homes are decorated with plants and flowers on Shavuot, commemorating the greenery that miraculously sprouted on Har Sinai when the Torah was given. It's the one time your shul looks like a botanical garden."},
    {id: 31, title: "All Night Learning", cat: "Food & Customs", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "Communities worldwide stay up the entire first night of Shavuot engaged in Torah study. Shiurim, chavruta sessions, and caffeine flow freely from sundown to sunrise. Sleep is for Sukkot."},
    {id: 32, title: "Bikkurim First Fruits", cat: "Food & Customs", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "In Temple times, farmers brought their first fruits to the Beit HaMikdash starting on Shavuot. The seven species of Eretz Yisrael were carried in decorated baskets with great fanfare. The original farm-to-table experience."},
    {id: 33, title: "Shtei HaLechem", cat: "Food & Customs", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "The Two Loaves of chametz bread offered in the Beit HaMikdash on Shavuot — the only chametz offering on the mizbeach all year. Made from the new wheat harvest, they were a thanksgiving for the grain season."},
    {id: 34, title: "Sinai Covered In Grass", cat: "Food & Customs", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "Tradition holds that the normally barren Har Sinai bloomed with lush greenery when Hashem descended to give the Torah. This miracle is one reason we decorate with plants. Even the desert wanted to dress up for the occasion."},
    {id: 35, title: "Honey And Torah", cat: "Food & Customs", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The custom of eating honey on Shavuot comes from Shir HaShirim: 'Honey and milk are under your tongue.' Some have the tradition of giving children honey-coated letters when they start learning Torah, so Torah should always taste sweet."},
    {id: 36, title: "Tikun Reading Booklet", cat: "Food & Customs", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "The Tikun Leil Shavuot booklet, compiled by kabbalists, contains selections from every parsha, Mishnah, and Zohar passage. It's designed as a spiritual sampler platter — a taste of every part of Torah in one epic night."},
    {id: 37, title: "Second Day Shavuot", cat: "Food & Customs", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "Outside of Israel, Shavuot is celebrated for two days due to the historical uncertainty of the calendar. In Israel it's just one day, giving Israelis a legitimate reason to feel smug about their chag schedule."},
    {id: 38, title: "Shavuot Flower Crowns", cat: "Food & Customs", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "In many communities, children make and wear flower crowns on Shavuot, symbolizing the crowns that the angels placed on each Jew's head when they said 'Naaseh V'Nishma.' Adorable and deeply meaningful."},

    // ===== FUN & SILLY (12 cards) =====
    {id: 39, title: "Falling Asleep During Tikkun", cat: "Fun & Silly", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "You swore you'd make it through the whole night. You were doing great at midnight. By 2am the Gemara started getting blurry. By 3am you were using the Tikun booklet as a pillow. No judgement — even Bnei Yisrael overslept."},
    {id: 40, title: "Cheesecake Competition", cat: "Fun & Silly", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "Every shul potluck becomes a covert cheesecake bake-off. There's the classic, the 'I added a twist,' the store-bought-pretending-to-be-homemade, and the one that's somehow still frozen in the middle. Everyone votes with their forks."},
    {id: 41, title: "Coffee At Four AM", cat: "Fun & Silly", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The most important beverage in Shavuot history. By 4am, coffee isn't a preference — it's a survival mechanism. The real miracle of Shavuot is that instant coffee can keep an entire shul conscious for Shacharit."},
    {id: 42, title: "Staying Up For Shacharit", cat: "Fun & Silly", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "The ultimate Shavuot challenge: you stayed up all night, you can see the sunrise, but can you actually stand for Shemoneh Esrei without swaying from exhaustion rather than kavanah? Bonus points if you don't yawn during kedusha."},
    {id: 43, title: "Best Dairy Debate", cat: "Fun & Silly", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "Is cheesecake the true queen of Shavuot, or do blintzes reign supreme? What about lasagna, pizza, or ice cream? This debate has divided more families than the question of gebrokts on Pesach."},
    {id: 44, title: "Shortest Chag Debate", cat: "Fun & Silly", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "Shavuot is technically only one day in Israel (two in the diaspora), has no sukkah to build, no matzah to buy, and no shofar to practice. Some call it the 'low-maintenance chag.' Others call it underappreciated. Both are correct."},
    {id: 45, title: "Kids Flower Crown Chaos", cat: "Fun & Silly", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "It started as a beautiful craft project. Within minutes, petals are everywhere, glue is on the carpet, and someone is crying because their crown fell apart. But the Instagram photo will look adorable, and that's what matters."},
    {id: 46, title: "Lactose Intolerant Dilemma", cat: "Fun & Silly", pts: 2, type: "text", img: null, imgPrompt: "", culled: false, desc: "For some, Shavuot is less 'Festival of the Torah' and more 'Festival of the Tums.' The dairy-heavy menu is a spiritual delight but a digestive minefield. Lactaid pills become the real Shavuot essential."},
    {id: 47, title: "Oversleeping The Alarm", cat: "Fun & Silly", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "You set three alarms. Your chavruta was supposed to call you. You were only going to close your eyes for five minutes at 3am. Next thing you know, it's 10am and you've missed everything. The Bnei Yisrael at Sinai would be proud."},
    {id: 48, title: "Post Shavuot Nap", cat: "Fun & Silly", pts: 1, type: "text", img: null, imgPrompt: "", culled: false, desc: "The holiest nap of the Jewish calendar year. After being up all night, davening at sunrise, eating a dairy feast, and possibly a meat meal too, collapsing onto the couch feels like a mitzvah. And maybe it is."},
    {id: 49, title: "Forgotten Festival Problem", cat: "Fun & Silly", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "Pesach has the Seder, Sukkot has the Sukkah, Rosh Hashana has the Shofar, Chanukah has the Menorah. Shavuot has... cheesecake? No wonder people forget it's coming. Shavuot's PR team needs a serious overhaul."},
    {id: 50, title: "Dairy Then Meat Logistics", cat: "Fun & Silly", pts: 3, type: "text", img: null, imgPrompt: "", culled: false, desc: "The Shavuot meal planning puzzle: start with dairy because minhag, then wait the required time, then have the meat seudah because Yom Tov. Requires a spreadsheet, three tablecloths, and military-grade dishwashing coordination."}
  ]
};
